QuanLySieuthimini1/Models/Nhomhang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace QuanLySieuthimini1.Models
{
    public class Nhomhang
    {
        [Key, Required]
        [Display(Name = "Mã Nhóm Hàng")]
        public int Ma_NH { get; set; }
        [Required]
        [Display(Name = "Tên Nhóm Hàng")]
        public string Ten_NH { get; set; }
        public virtual ICollection<Hanghoa> Hanghoas { get; set; }
        public virtual ICollection<Chitiethanghoa> Chitiethanghoas { get; set; }

    }
}

QuanLySieuthimini1/Areas/Admin/Controllers/NhomhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySieuthimini1.Models;

namespace QuanLySieuthimini1.Areas.Admin.Controllers
{
    public class NhomhangsController : Controller
    {
        private ConnectDB db = new ConnectDB();

        // GET: Admin/Nhomhangs
        public ActionResult Index()
        {
            return View(db.Nhomhangs.ToList());
        }

        // GET: Admin/Nhomhangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // GET: Admin/Nhomhangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Nhomhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Nhomhangs.Add(nhomhang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhomhang);
        }

        // GET: Admin/Nhomhangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Admin/Nhomhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhomhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhomhang);
        }

        // GET: Admin/Nhomhangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Admin/Nhomhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            db.Nhomhangs.Remove(nhomhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySieuthimini1/Areas/Staff/Controllers/HomessController.cs
using QuanLySieuthimini1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QuanLySieuthimini1.Areas.Staff.Controllers
{
    public class HomessController : Controller
    {
        ConnectDB db = new ConnectDB();
        // GET: Staff/Homess
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Dangxuat()
        {
            Session.Abandon();//remove session
            return Redirect("/Home/Dangnhap");
        }
    }
}

QuanLySieuthimini1/Areas/Staff/Controllers/NhomhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySieuthimini1.Models;

namespace QuanLySieuthimini1.Areas.Staff.Controllers
{
    public class NhomhangsController : Controller
    {
        private ConnectDB db = new ConnectDB();

        // GET: Staff/Nhomhangs
        public ActionResult Index()
        {
            return View(db.Nhomhangs.ToList());
        }

        // GET: Staff/Nhomhangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // GET: Staff/Nhomhangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/Nhomhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Nhomhangs.Add(nhomhang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhomhang);
        }

        // GET: Staff/Nhomhangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Staff/Nhomhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhomhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhomhang);
        }

        // GET: Staff/Nhomhangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Staff/Nhomhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            db.Nhomhangs.Remove(nhomhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySieuthimini1/Controllers/NhomhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySieuthimini1.Models;

namespace QuanLySieuthimini1.Controllers
{
    public class NhomhangsController : Controller
    {
        private ConnectDB db = new ConnectDB();

        // GET: Nhomhangs
        public ActionResult Index()
        {
            if (Session["idNhanvien"] == null)
            {
                return RedirectToAction("Dangnhap", "Home");
            }
            return View(db.Nhomhangs.ToList());
        }

        // GET: Nhomhangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // GET: Nhomhangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Nhomhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Nhomhangs.Add(nhomhang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhomhang);
        }

        // GET: Nhomhangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Nhomhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Ma_NH,Ten_NH")] Nhomhang nhomhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhomhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhomhang);
        }

        // GET: Nhomhangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            if (nhomhang == null)
            {
                return HttpNotFound();
            }
            return View(nhomhang);
        }

        // POST: Nhomhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nhomhang nhomhang = db.Nhomhangs.Find(id);
            db.Nhomhangs.Remove(nhomhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySieuthimini1/Areas/Staff/Views/Nhomhangs/Create.cshtml
@model QuanLySieuthimini1.Models.Nhomhang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Staff/Views/Shared/_Layout.cshtml";
}

<h2>Thêm mới nhóm hàng</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ten_NH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_NH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_NH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

QuanLySieuthimini1/Areas/Staff/Views/Nhomhangs/Delete.cshtml
@model QuanLySieuthimini1.Models.Nhomhang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Staff/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có chắc chắn muốn xoá mục này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten_NH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_NH)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

QuanLySieuthimini1/Areas/Staff/Views/Nhomhangs/Details.cshtml
@model QuanLySieuthimini1.Models.Nhomhang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Staff/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin chi tiết của nhóm hàng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten_NH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_NH)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Ma_NH }) |
    @Html.ActionLink("Quay Lại", "Index")
</p>

QuanLySieuthimini1/Areas/Staff/Views/Nhomhangs/Edit.cshtml
@model QuanLySieuthimini1.Models.Nhomhang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Staff/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin của nhóm hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Ma_NH)

        <div class="form-group">
            @Html.LabelFor(model => model.Ten_NH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_NH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_NH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

QuanLySieuthimini1/Areas/Staff/Views/Nhomhangs/Index.cshtml
@model IEnumerable<QuanLySieuthimini1.Models.Nhomhang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Staff/Views/Shared/_Layout.cshtml";
}



<p>
    
    
</p>
<table class="table">
    <tr>
        <th>
            <h2>Danh sách nhóm hàng</h2>
        </th>
        <th>
            @Html.ActionLink("Thêm Mới", "Create")
        </th>
        <th>
            @Html.ActionLink("Quay Lại", "Index", "Homess")
        </th>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ma_NH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ten_NH)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Ma_NH)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ten_NH)
    </td>
    <td>
        @Html.ActionLink("Sửa", "Edit", new { id = item.Ma_NH }) |
        @Html.ActionLink("Chi tiết", "Details", new { id = item.Ma_NH }) |
        @Html.ActionLink("Xoá", "Delete", new { id = item.Ma_NH })
    </td>
</tr>
}

</table>